julia euler8.jl data1.txt
julia euler8.jl data2.txt
julia euler8.jl data3.txt
julia euler8.jl data4.txt
julia euler8.jl data5.txt
julia euler8.jl data6.txt
julia euler8.jl data7.txt
julia euler8.jl data8.txt
julia euler8.jl data9.txt
julia euler8.jl data10.txt