#=

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=#
#Answer: 76576500

#Terminal: julia euler12.jl 500
numDiv = parse(Int, ARGS[1])
function divisors(n)
  numFactors = 0
  ceiling = typemax(Int32)
  for i in range(1, Int(ceil(sqrt(n)+1)))
    if n % i == 0
      numFactors += 2
    end
    if i*i == n
      numFactors -= 1
    end
  end
  return numFactors
end

function triangular(numDiv)
  ceil = typemax(Int16)
  for n = 1 : ceil
    k = Int((n*(n+1))/2)
    if n % 2 == 0
      count = divisors(n / 2) * divisors(n + 1)
    else
      count = divisors(n) * divisors((n + 1) / 2)
    end
    if count > numDiv
      return k
    end
  end
end

println(triangular(numDiv))
